{{- if .Values.skypilot.apiService.customEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  # Note: replicas > 1 is not well tested, and requires a PVC that supports ReadWriteMany.
  replicas: {{ .Values.skypilot.apiService.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
        # This label indicates that the API server is ready to serve requests.
        skypilot.co/ready: "true"
    spec:
      automountServiceAccountToken: {{ .Values.skypilot.kubernetesCredentials.useApiServerCluster }}
      serviceAccountName: {{ include "custom.skypilot.serviceAccountName" . }}
      {{- with .Values.skypilot.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      runtimeClassName: {{ .Values.skypilot.runtimeClassName }}
      containers:
      - name: skypilot-api
        image: {{ .Values.skypilot.apiService.image }}
        imagePullPolicy: Always
        {{- with .Values.skypilot.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.skypilot.apiService.resources | nindent 10 }}
        env:
        - name: SKYPILOT_DEV
          value: {{ .Values.skypilot.apiService.skypilotDev | quote }}
        {{- if .Values.skypilot.gcpCredentials.enabled }}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /root/gcp-cred.json
        {{- end }}
        {{- if .Values.skypilot.kubernetesCredentials.inclusterNamespace }}
        - name: SKYPILOT_IN_CLUSTER_NAMESPACE
          value: {{ .Values.skypilot.kubernetesCredentials.inclusterNamespace }}
        {{- end }}
        # Use tini as the init process
        command: ["tini", "--"]
        # Start API server in foreground (if supported) to:
        # 1. Bypass the healthz check of `sky api start`, let kubernetes probes manage the lifecycle directly.
        # 2. Capture all logs in container to stdout/stderr, bypass in-container log file overhead.
        # 3. Exec ensures the process is a direct child of tini, enables correct signal handling.
        # Note: this comment is moved here to avoid appearing in the final start script.
        args:
        - /bin/sh
        - -c
        - |
          set -e
          {{- if .Values.skypilot.apiService.preDeployHook }}
          {{ .Values.skypilot.apiService.preDeployHook | nindent 10 }}
          {{- end }}
          {{- if .Values.skypilot.apiService.customConfig }}
          mkdir -p /root/.sky
          echo "Copying config.yaml from ConfigMap \`skypilot-config\` to /root/.sky/config.yaml"
          # The configmap serves as the ground truth for the config.yaml file, read-only
          ln -sf /var/skypilot/config/config.yaml /root/.sky/config.yaml
          {{- end }}

          if sky api start -h | grep -q -- "--foreground"; then
            exec sky api start --deploy --foreground
          else
            # For backward compatibility, run in background if --foreground is not supported.
            # TODO(aylei): this will bedropped in 0.11.0.
            if sky api start --deploy; then
              tail -n+0 -f /root/.sky/api_server/server.log
            else
              cat /root/.sky/api_server/server.log
            fi
          fi
        ports:
        - containerPort: 46580
        livenessProbe:
          httpGet:
            path: /api/health
            port: 46580
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/health
            port: 46580
          periodSeconds: 30
        volumeMounts:
        {{- if .Values.skypilot.storage.enabled }}
        - name: state-volume
          mountPath: /root/.sky
          subPath: .sky
        - name: state-volume
          mountPath: /root/.ssh # To preserve the SSH keys for the user when using the API server
          subPath: .ssh
        {{- end }}
        {{- if .Values.skypilot.apiService.customConfig }}
        - name: skypilot-config
          mountPath: /var/skypilot/config
        {{- end }}
        {{- if .Values.skypilot.awsCredentials.enabled }}
        - name: aws-config
          mountPath: /root/.aws
          readOnly: true
        {{- end }}
        {{- if .Values.skypilot.gcpCredentials.enabled }}
        - name: gcp-config
          mountPath: /root/.config/gcloud
        - name: gcp-credentials
          mountPath: /root/gcp-cred.json
          subPath: gcp-cred.json
        {{- end }}
        {{- if .Values.skypilot.kubernetesCredentials.useKubeconfig }}
        - name: kube-config
          mountPath: /root/.kube
        {{- end }}
        {{- if .Values.skypilot.runpodCredentials.enabled }}
        - name: runpod-config
          mountPath: /root/.runpod/config.toml
          subPath: {{ .Values.skypilot.runpodCredentials.runpodSecretKey }}
          readOnly: true
        {{- end }}
        {{- if .Values.skypilot.lambdaCredentials.enabled }}
        - name: lambda-config
          mountPath: /root/.lambda_cloud
          readOnly: true
        {{- end }}
      initContainers:
      {{- if .Values.skypilot.awsCredentials.enabled }}
      - name: create-aws-credentials
        {{- with .Values.skypilot.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: {{ .Values.skypilot.apiService.image }}
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Setting up AWS credentials..."
          if [ -n "$AWS_ACCESS_KEY_ID" ] && [ -n "$AWS_SECRET_ACCESS_KEY" ]; then
            echo "AWS credentials found in environment variables."
            aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
            aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
            echo "Credentials file created successfully."
          else
            echo "AWS credentials not found in environment variables. Skipping credentials setup."
            sleep 600
          fi
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.skypilot.awsCredentials.awsSecretName }}
              key: {{ .Values.skypilot.awsCredentials.accessKeyIdKeyName }}
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.skypilot.awsCredentials.awsSecretName }}
              key: {{ .Values.skypilot.awsCredentials.secretAccessKeyKeyName }}
        volumeMounts:
        - name: aws-config
          mountPath: /root/.aws
      {{- end }}
      {{- if .Values.skypilot.gcpCredentials.enabled }}
      - name: setup-gcp-credentials
        {{- with .Values.skypilot.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: google/cloud-sdk:latest
        command: ["/bin/sh", "-c"]
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /root/gcp-cred.json
        args:
        - |
          gcloud auth activate-service-account --key-file=/root/gcp-cred.json
          gcloud config set project {{ .Values.skypilot.gcpCredentials.projectId }}
        volumeMounts:
        - name: gcp-credentials
          mountPath: /root/gcp-cred.json
          subPath: gcp-cred.json
        - name: gcp-config
          mountPath: /root/.config/gcloud
      {{- end }}
      {{- if .Values.skypilot.lambdaCredentials.enabled }}
      - name: create-lambda-credentials
        {{- with .Values.skypilot.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: {{ .Values.skypilot.apiService.image }}
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Setting up Lambda credentials..."
          if [ -n "$LAMBDA_API_KEY" ]; then
            echo "Lambda credentials found in environment variable."
            mkdir -p /root/.lambda_cloud
            echo "api_key = $LAMBDA_API_KEY" > /root/.lambda_cloud/lambda_keys
          else
            echo "Lambda credentials not found in environment variables. Skipping credentials setup."
            sleep 600
          fi
        env:
        - name: LAMBDA_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.skypilot.lambdaCredentials.lambdaSecretName }}
              key: api_key
        volumeMounts:
        - name: lambda-config
          mountPath: /root/.lambda_cloud
      {{- end }}
      volumes:
      {{- if .Values.skypilot.storage.enabled }}
      - name: state-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-state
      {{- else }}
      - name: state-volume
        emptyDir: {}
      {{- end }}
      {{- if .Values.skypilot.awsCredentials.enabled }}
      - name: aws-config
        emptyDir: {}
      {{- end }}
      {{- if .Values.skypilot.gcpCredentials.enabled }}
      - name: gcp-credentials
        secret:
          secretName: {{ .Values.skypilot.gcpCredentials.gcpSecretName }}
      - name: gcp-config
        emptyDir: {}
      {{- end }}
      {{- if .Values.skypilot.runpodCredentials.enabled }}
      - name: runpod-config
        secret:
          secretName: {{ .Values.skypilot.runpodCredentials.runpodSecretName }}
      {{- end }}
      {{- if .Values.skypilot.lambdaCredentials.enabled }}
      - name: lambda-config
        emptyDir: {}
      {{- end }}
      {{- if .Values.skypilot.kubernetesCredentials.useKubeconfig }}
      - name: kube-config
        secret:
          secretName: {{ .Values.skypilot.kubernetesCredentials.kubeconfigSecretName }}
      {{- end }}
      {{- if .Values.skypilot.apiService.customConfig }}
      - name: skypilot-config
        configMap:
          name: {{ .Release.Name }}-config
      {{- end }}
{{- end }}
