apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: { { .Release.Name } }
  namespace: keda
  annotations:
    kubernetes.io/ingress.global-static-ip-name: { { .Release.Name } }
    kubernetes.io/ingress.class: gce
    networking.gke.io/managed-certificates: { { .Release.Name } }
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/v1beta1.FrontendConfig: { { .Release.Name } }
    external-dns.alpha.kubernetes.io/hostname: { { .Values.domain } }
spec:
  ingressClassName: gce
  defaultBackend:
    service:
      name: keda-add-ons-http-interceptor-proxy
      port:
        name: proxy
  rules:
    - host: { { .Values.domain } }
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keda-add-ons-http-interceptor-proxy
                port:
                  name: proxy
