apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: interceptor
  namespace: keda
spec:
  timeoutSec: {{ .Values.requestTimeoutSeconds }}
  connectionDraining:
    drainingTimeoutSec: {{ .Values.requestTimeoutSeconds }}
  healthCheck:
    requestPath: /health
    port: 8080 # default Interceptor port
    type: HTTP
