apiVersion: v1
kind: Service
metadata:
  name: keda-add-ons-http-interceptor-proxy
  namespace: keda
  annotations:
    cloud.google.com/app-protocols: '{"proxy":"HTTP"}'
    cloud.google.com/backend-config: '{"default": "interceptor", "ports": {"proxy":"interceptor"}}'
