activation_dropout: 0.0
attention_dropout: 0.0
attn_implementation: sdpa
base_hf_repo: mms-meta/mms-zeroshot-300m
data_seed: 42
dataloader_num_workers: 4
decay_ratio: 1.0
effective_batch_size: 16
eval_limit: 1000
eval_on_start: true
eval_size: 20000
eval_steps: 100
feat_proj_dropout: 0.0
feat_quantizer_dropout: 0.0
final_dropout: 0.0
fp16: false
hf_user: Kellner
hidden_dropout: 0.0
layerdrop: 0.0
learning_rate: 0.01
logging_steps: 10
mega_batch_mult: 100
num_devices: 1
num_train_epochs: null
num_training_steps: 200
padding_side: random
per_device_eval_batch_size: 8
per_device_eval_batch_total_seconds: 90.0
per_device_train_batch_size: 4
per_device_train_batch_total_seconds: 90.0
raw_eval_size: 11290
raw_train_size: 35147
sample_rate: 16000
save_steps: 100
seed: 42
should_demo: false
should_push: false
steps_per_epoch: 1050
target_hf_repo: mms-300m-turkish
target_lang: tur
tokenizer_hf_repo: mms-meta/mms-zeroshot-300m
torch_compile: false
train_limit: 100000
train_size: 100000
warmup_ratio: 0.0
weight_decay: 0.01
