services:
  example:
    build:
      context: .
      dockerfile: ./src/example.Dockerfile
      args:
        WORKDIR: ${WORKDIR}
    networks:
      - finetune-setup-example
networks:
  finetune-setup-example:
    external: true
