services:
  train:
    env_file:
      - ./src/train.env
    build:
      context: .
      dockerfile: ./src/train.Dockerfile
      args:
        WORKDIR: ${WORKDIR}
    networks:
      - finetune-setup-example
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  finetune-setup-example:
    external: true
